# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c8b76d8cdccd39ae45b847901d4b4fb3"
name = "reviews"
application_url = "https://maui-become-desktops-tournament.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "developmentcheck.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://maui-become-desktops-tournament.trycloudflare.com/auth/callback",
  "https://maui-become-desktops-tournament.trycloudflare.com/auth/shopify/callback",
  "https://maui-become-desktops-tournament.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
